version: "3.3"

volumes:
  vendor:

services:
  web:
    #  can be specified either as a string containing a path to the build context:
    build: .
    ports:
      - "8000:80"
    # @see https://docs.docker.com/compose/compose-file/ depends_on
    depends_on:
      - sql
    links:
      - "sql:database"
    volumes:
      - "./src:/var/www/html"
      - "vendor:/var/www/html/vendor"
  sql:
    image: mariadb:${MYSQL_VERSION}
    container_name: mysql_gadgets
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "/var/lib/mysql"
